import type { RouteCopy } from "./content";

export const enUS = {
  languageName: "中文",
  nav: {
    product: "Product",
    studio: "Studio",
    architecture: "Architecture",
    publication: "Publication",
    docs: "Docs",
    changelog: "Changelog",
    github: "GitHub",
    menu: "Open navigation",
    close: "Close navigation",
    appearance: "Toggle appearance",
  },
  home: {
    eyebrow: "AI-native fiction authoring framework · 0.9.1",
    title: "A fiction system that can show what it knew, what passed, and what changed.",
    lede: "Quillframe treats long-form fiction as an inspectable creative system: context is grounded, characters only act on evidence they can know, quality gates bind to the exact candidate, and accepted text can travel into deterministic publication without silently changing the manuscript.",
    primaryCta: "Explore the forge",
    secondaryCta: "See the architecture",
    proofLabel: "Proof, not promises",
    problem: {
      eyebrow: "The problem",
      title: "A prompt can make prose. A novel needs memory with rules.",
      lede: "One-shot generation is good at producing text. It is much worse at preserving authority, perspective, continuity, and repair history across a living book.",
      cards: [
        { title: "Context without leakage", body: "Relevant evidence is not enough. Quillframe also checks visibility, story order, stage eligibility, authority, and the hard packet budget before evidence can reach the model." },
        { title: "Characters with epistemic limits", body: "A character action cannot cite future, unknown, or perspective-incompatible evidence as positive support just because the framework stores it somewhere." },
        { title: "Quality without fake scores", body: "Surface, reader engagement, continuity, and independent semantic review remain distinct typed gates. Readiness is a conjunction, not a made-up 8.7/10." },
      ],
    },
    forge: {
      eyebrow: "The forge",
      title: "Creative judgment where it belongs. Deterministic boundaries everywhere else.",
      lede: "The model judges fiction semantics. Code owns authority, visibility, fingerprints, budgets, persistence, typed validation, and transactions.",
      steps: [
        ["01", "Project", "Canon, plans, characters, relationships, research, and current work remain distinct authority classes."],
        ["02", "Context", "Question-bound evidence is filtered for visibility and story order before semantic selection."],
        ["03", "Simulation", "Story, character, reader pressure, and consequence are resolved before line-level surface polish."],
        ["04", "Draft", "Generation consumes a frozen packet; private reasoning and hidden regression material stay outside writer context."],
        ["05", "Gates", "Surface, reader engagement, continuity, and required independent semantic review bind to one candidate fingerprint."],
        ["06", "User-visible", "Only a candidate that satisfies the current gate policy may cross into review; acceptance and settlement remain separate."],
      ],
    },
    proofs: [
      { eyebrow: "Context", title: "Support ≠ loaded context", body: "Run Receipts distinguish evidence selected as support from evidence that actually entered the bounded packet — including budget drops and visibility exclusions.", meta: "quillframe_run_receipt_v1" },
      { eyebrow: "Readiness", title: "One fingerprint, all required gates", body: "The production-readiness record fails closed when required Surface, Reader Engagement, Continuity, or independent semantic evidence is missing, pending, or failing.", meta: "quillframe_production_readiness_v1" },
      { eyebrow: "Character", title: "Knowledge has a story-time boundary", body: "Epistemic status and acquisition mode are separate, and proposed actions must be backed by character-visible, story-ordered evidence.", meta: "character evidence contract" },
      { eyebrow: "Publication", title: "Accepted text stays exact", body: "Publication IR checks source fingerprints and preserves exact Unicode manuscript text while producing derived clean text, Web HTML, print-oriented HTML/CSS, and EPUB 3.3.", meta: "quillframe_publication_ir_v1" },
      { eyebrow: "Hosts", title: "Capability never becomes authority", body: "CLI, Desktop, hosted UI, and Agent Skill may expose different capabilities. Host access never grants Canon, Framework-write, or Settlement authority.", meta: "authority=false" },
      { eyebrow: "Persistence", title: "SQLite is the canonical database", body: "Global and per-project SQLite stores own durable product state through the typed Core boundary. Autosave, revision, acceptance, and settlement remain distinct transitions.", meta: "SQLite-native" },
    ],
    studio: {
      eyebrow: "Studio",
      title: "A creator workbench, not a runtime dashboard with a manuscript tab.",
      lede: "Writer Mode starts from the work: manuscript, plan, story, review, research, learning, and publish. Inspector Mode reveals sessions, runs, context, capabilities, model execution evidence, and diagnostics only when you need them.",
      bullets: ["SolidJS + TypeScript + Vite", "Tauri 2 thin desktop host", "Borderless Kawaii Editorial", "Typed Host Bridge over Python Core"],
      cta: "Explore Studio",
    },
    publication: {
      eyebrow: "Publication",
      title: "Accepted manuscript in. Deterministic derived formats out.",
      lede: "The publication core preserves exact accepted text, validates fingerprints, and builds explicit derived profiles without turning output into Canon.",
      profiles: ["clean_text", "web_reflow", "print_book", "epub3"],
      note: "Publication output remains derived state. Release-grade format validation stays separate from manuscript authority.",
      cta: "Publication details",
    },
    architecture: {
      eyebrow: "Architecture",
      title: "One system, distinct responsibilities.",
      lede: "Quillframe is intentionally not an agent round-table. Each subsystem owns a bounded mechanism and emits typed evidence for the next boundary.",
      cards: [
        { eyebrow: "Project", title: "Canon & state", body: "Authority classes, dependencies, accepted state, plans, and settlement evidence stay explicit." },
        { eyebrow: "Runtime", title: "Harness & sessions", body: "Manager sessions, runs, checkpoints, capabilities, handoffs, fingerprints, and consume-once evidence." },
        { eyebrow: "Story", title: "Simulation & character", body: "Causal story mechanics, character agendas, knowledge, relationships, and long-horizon reconciliation." },
        { eyebrow: "Editorial", title: "Reader & surface", body: "Reader pressure, engagement, anti-AI surface fundamentals, candidate evolution, and narrow repair routing." },
        { eyebrow: "Evidence", title: "Corpus & learning", body: "Rights-aware benchmarks, preference evidence, counterexamples, rollbackable hypotheses, and no Canon leakage." },
        { eyebrow: "Product", title: "Studio & publication", body: "Typed host boundaries, SQLite-native persistence, deterministic publication, and inspectable product proof." },
      ],
      cta: "Open architecture",
    },
    delivery: {
      eyebrow: "One product, many hosts",
      title: "Use the interface that fits the work — without changing story truth.",
      hosts: [
        ["CLI", "Scriptable automation and inspection."],
        ["Desktop", "Tauri 2 thin host over the same typed Core boundary."],
        ["Hosted UI", "The SolidJS product surface behind an authenticated remote Core when one is configured."],
        ["Agent Skill", "Portable Quillframe agent integration without private persistence imports."],
      ],
    },
    release: {
      eyebrow: "Release truth",
      title: "0.9.1 is the current pre-1.0 release line.",
      lede: "Quillframe 0.9 converges the active product on SolidJS, Tauri 2, Python Core, SQLite-native persistence, typed Host Bridge contracts, and Astro/Starlight documentation. Pre-1.0 still permits justified breaking cleanup, but active surfaces no longer present the old 0.8 architecture as current.",
      cta: "Read the changelog",
    },
    final: {
      title: "Read the system. Inspect the proof. Then decide if it fits your fiction workflow.",
      docs: "Browse documentation",
      github: "View on GitHub",
    },
  },
  routes: {
    product: {
      eyebrow: "Product model",
      title: "Quillframe is a fiction production system, not a prompt wrapper.",
      lede: "It separates creative judgment from deterministic control so a long-running book can accumulate evidence, revisions, and state without turning every previous model output into truth.",
      cards: [
        { title: "Authority before convenience", body: "Locked, accepted, active plan, review, proposal, derived, runtime, learning, and corpus material are not interchangeable." },
        { title: "Evidence before confidence", body: "Context and character decisions can expose exactly what support existed, what was eligible, and what actually entered the active packet." },
        { title: "Repair the owning mechanism", body: "Surface clusters regenerate scenes; reader-grip failures return to Reader Pressure and Scene Simulation; story failures return to Story mechanics." },
        { title: "Acceptance is a real boundary", body: "A review candidate is not Canon. User acceptance and exact settlement remain explicit transitions with fingerprints and before/after evidence." },
      ],
    },
    studio: {
      eyebrow: "Quillframe Studio",
      title: "The authoring environment around Core — with runtime detail only when it helps the work.",
      lede: "The 0.9 Studio is SolidJS + TypeScript + Vite with a Tauri 2 thin host path, responsive Writer/Inspector information architecture, a typed Host Bridge, and no direct SQLite access from UI code.",
      cards: [
        { eyebrow: "Writer", title: "Authoring first", body: "Desk, manuscript, plan, story, review, research, learning, and publish remain the primary product mental model." },
        { eyebrow: "Runtime", title: "Real Core workflows", body: "Session, Run, Checkpoint, Context and Receipt surfaces consume typed Core projections instead of browser-fabricated production state." },
        { eyebrow: "Models", title: "Model Service abstraction", body: "Users connect a Model API with API Endpoint + Access Token. Model discovery and capability evidence are runtime observations; automatic model selection is the default." },
        { eyebrow: "Inspector", title: "Evidence on demand", body: "Advanced runtime, execution, capability and provenance detail stays inspectable without turning Studio into an infrastructure dashboard." },
      ],
    },
    architecture: {
      eyebrow: "System architecture",
      title: "Generic mechanisms stay generic. Project truth stays in the project.",
      lede: "Quillframe defines reusable Story, Character, Canon, Context, Quality, Runtime, Learning, Corpus, Publication, Persistence, and Product contracts. Consumer novels supply their own characters, world, plans, state, manuscript, and accepted Canon.",
      cards: [
        { title: "Host boundary", body: "Hosts run sessions, model/tool loops, sandboxes, and subagents; Quillframe keeps novel-contract, Context, review, and Settlement semantics." },
        { title: "Context", body: "Sparse question-bounded evidence with visibility, story-order, authority, and hard-budget enforcement." },
        { title: "Semantic contracts", body: "Typed model judgments with fingerprints; deterministic validators enforce shape and ownership, not literary taste." },
        { title: "Quality", body: "Reader, continuity, character, surface, and independent semantic evidence converge at an explicit readiness boundary." },
        { title: "Persistence", body: "SQLite is canonical durable state. Backups, migrations, WAL, integrity checks, revisions and blobs remain Core-owned." },
        { title: "Publication", body: "Exact-text Accepted manuscript compilation into deterministic, derived publication artifacts." },
      ],
    },
    publication: {
      eyebrow: "Deterministic publication",
      title: "Publication is derived output — never a second manuscript authority.",
      lede: "The compiler binds to accepted text fingerprints and preserves exact Unicode chapter text. Broader typesetting remains deliberately separate from manuscript authority.",
      cards: [
        { title: "clean_text", body: "A deterministic clean-text representation of Accepted manuscript content." },
        { title: "web_reflow", body: "Reflowable Web HTML derived from the same exact-text Publication IR." },
        { title: "print_book", body: "Print-oriented HTML/CSS derived from accepted text without becoming a second live manuscript." },
        { title: "epub3", body: "Deterministic EPUB 3 generation with validation kept separate from Canon authority." },
      ],
      note: "Publication artifacts are outputs of accepted source state, not a second editable authority layer.",
    },
    docs: {
      eyebrow: "Documentation",
      title: "Deep contracts when you need them. Product story when you do not.",
      lede: "The public site does not replace repository documentation. These links lead to maintained sources that define current behavior and boundaries.",
      cards: [
        { eyebrow: "Start", title: "Docs Home", body: "Task-oriented entry into architecture, runtime, quality, projects, Studio, and release truth.", meta: "docs/README.en.md" },
        { eyebrow: "Core", title: "Architecture Atlas", body: "Subsystem map and contract-oriented architecture reference.", meta: "docs/architecture-atlas.en.md" },
        { eyebrow: "Production", title: "Production Pipeline", body: "From context freeze and simulation through user-visible review and settlement boundaries.", meta: "docs/production-pipeline.en.md" },
        { eyebrow: "Quality", title: "Quality Assurance", body: "Surface, Reader Engagement, Continuity, and semantic gate semantics.", meta: "docs/quality-assurance.en.md" },
        { eyebrow: "Product", title: "Studio Architecture", body: "Writer/Inspector product model, typed Host Bridge, SolidJS Studio, Tauri host direction, and current boundaries.", meta: "studio/PRODUCT_ARCHITECTURE.en.md" },
        { eyebrow: "Release", title: "0.9.1 Changelog", body: "Novel-native host boundary, exact review evidence, mapped projection, and the distinction between implemented behavior and remaining work.", meta: "CHANGELOG.en.md" },
      ],
    },
    changelog: {
      eyebrow: "Release truth",
      title: "A changelog that separates implementation from aspiration.",
      lede: "Quillframe is pre-1.0. The current ledger records machine/product behavior and keeps remaining Core/Product gaps explicit rather than silently promoting roadmaps into capabilities.",
      cards: [
        { title: "0.9.1 identity", body: "Manifest, CLI, Studio, persistence, Project SDK, technical namespace, and documentation use one current Quillframe identity." },
        { title: "Breaking cleanup is still possible", body: "Before 1.0, justified contract cleanup may land when architecture and deterministic CI support it." },
        { title: "History stays history", body: "Older 0.8/7.x records retain their original meaning; active product surfaces do not present them as current architecture." },
      ],
    },
  } satisfies Record<string, RouteCopy>,
} as const;
