import type { RouteCopy } from "./content";

export const enUS = {
  languageName: "中文",
  nav: {
    product: "Product",
    studio: "Studio",
    architecture: "Architecture",
    publication: "Publication",
    docs: "Docs",
    changelog: "Changelog",
    github: "GitHub",
    menu: "Open navigation",
    close: "Close navigation",
    appearance: "Toggle appearance",
  },
  home: {
    eyebrow: "Adaptive fiction agent framework · 0.8.x",
    title: "A fiction system that can show what it knew, what passed, and what changed.",
    lede: "Quillframe treats long-form fiction as an inspectable creative system: context is grounded, characters only act on evidence they can know, quality gates bind to the exact candidate, and accepted text can travel into deterministic publication without silently changing the manuscript.",
    primaryCta: "Explore the forge",
    secondaryCta: "See the architecture",
    proofLabel: "Proof, not promises",
    problem: {
      eyebrow: "The problem",
      title: "A prompt can make prose. A novel needs memory with rules.",
      lede: "One-shot generation is good at producing text. It is much worse at preserving authority, perspective, continuity, and repair history across a living book.",
      cards: [
        { title: "Context without leakage", body: "Relevant evidence is not enough. Quillframe also checks visibility, story order, stage eligibility, authority, and the hard packet budget before evidence can reach the model." },
        { title: "Characters with epistemic limits", body: "A character action cannot cite future, unknown, or perspective-incompatible evidence as positive support just because the framework stores it somewhere." },
        { title: "Quality without fake scores", body: "Surface, reader engagement, continuity, and independent semantic review remain distinct typed gates. Readiness is a conjunction, not a made-up 8.7/10." },
      ],
    },
    forge: {
      eyebrow: "The forge",
      title: "Creative judgment where it belongs. Deterministic boundaries everywhere else.",
      lede: "The model judges fiction semantics. Code owns authority, visibility, fingerprints, budgets, persistence, typed validation, and transactions.",
      steps: [
        ["01", "Project", "Canon, plans, characters, relationships, research, and current work remain distinct authority classes."],
        ["02", "Context", "Question-bound evidence is filtered for visibility and story order before semantic selection."],
        ["03", "Simulation", "Story, character, reader pressure, and consequence are resolved before line-level surface polish."],
        ["04", "Draft", "Generation consumes a frozen packet; private reasoning and hidden regression material stay outside writer context."],
        ["05", "Gates", "Surface, reader engagement, continuity, and required independent semantic review bind to one candidate fingerprint."],
        ["06", "User-visible", "Only a candidate that satisfies the current gate policy may cross into review; acceptance and settlement remain separate."],
      ],
    },
    proofs: [
      { eyebrow: "Context", title: "Support ≠ loaded context", body: "Run Receipts distinguish evidence selected as support from evidence that actually entered the bounded packet — including budget drops and visibility exclusions.", meta: "quillframe_run_receipt_v1" },
      { eyebrow: "Readiness", title: "One fingerprint, all required gates", body: "The production-readiness record fails closed when required Surface, Reader Engagement, Continuity, or independent semantic evidence is missing, pending, or failing.", meta: "quillframe_production_readiness_v1" },
      { eyebrow: "Character", title: "Knowledge has a story-time boundary", body: "Epistemic status and acquisition mode are separate, and proposed actions must be backed by character-visible, story-ordered evidence.", meta: "character evidence contract" },
      { eyebrow: "Publication", title: "Accepted text stays exact", body: "Publication IR checks source fingerprints and preserves exact Unicode manuscript text while producing derived clean text, Web HTML, print-oriented HTML/CSS, and EPUB 3.3.", meta: "quillframe_publication_ir_v1" },
      { eyebrow: "Hosts", title: "Capability never becomes authority", body: "CLI, Local Web, hosted UI, and Agent Skill may expose different capabilities. Host access never grants Canon, Framework-write, or Settlement authority.", meta: "authority=false" },
      { eyebrow: "Design", title: "The visual system is executable too", body: "Story Loom v2 pins the WeiUI zero-JavaScript foundation and machine-checks theme layering, contrast, touch size, locales, reduced motion, and no-default-polling rules.", meta: "quillframe_brand_tokens_v2" },
    ],
    studio: {
      eyebrow: "Studio",
      title: "A creator workbench, not a runtime dashboard with a manuscript tab.",
      lede: "Creator Mode starts from the work: manuscript, story, review, publication. Inspector Mode reveals runtime evidence only when you need it.",
      bullets: ["SolidJS + TypeScript + Vite", "Local Web first-class", "Config-generated WeiUI CSS, zero WeiUI runtime JS", "Optional Tauri installable host"],
      cta: "Explore Studio",
    },
    publication: {
      eyebrow: "Publication",
      title: "Accepted manuscript in. Deterministic derived formats out.",
      lede: "The minimum publication core already exists. It preserves exact accepted text, validates fingerprints, and builds four explicit profiles without turning output into Canon.",
      profiles: ["clean_text", "web_reflow", "print_book", "epub3"],
      note: "Current print_book output is print-oriented HTML/CSS, not a final paged-media PDF. Release EPUB conformance still requires external EPUBCheck.",
      cta: "Publication details",
    },
    architecture: {
      eyebrow: "Architecture",
      title: "One system, distinct responsibilities.",
      lede: "Quillframe is intentionally not an agent round-table. Each subsystem owns a bounded mechanism and emits typed evidence for the next boundary.",
      cards: [
        { eyebrow: "Project", title: "Canon & state", body: "Authority classes, dependencies, accepted state, plans, and settlement evidence stay explicit." },
        { eyebrow: "Runtime", title: "Harness & sessions", body: "Manager sessions, runs, checkpoints, capabilities, handoffs, fingerprints, and consume-once evidence." },
        { eyebrow: "Story", title: "Simulation & character", body: "Causal story mechanics, character agendas, knowledge, relationships, and long-horizon reconciliation." },
        { eyebrow: "Editorial", title: "Reader & surface", body: "Reader pressure, engagement, anti-AI surface fundamentals, candidate evolution, and narrow repair routing." },
        { eyebrow: "Evidence", title: "Corpus & learning", body: "Rights-aware benchmarks, preference evidence, counterexamples, rollbackable hypotheses, and no Canon leakage." },
        { eyebrow: "Product", title: "Studio & publication", body: "Portable read boundaries, Local Web, Agent Skill, deterministic publication, and inspectable product proof." },
      ],
      cta: "Open architecture",
    },
    delivery: {
      eyebrow: "One product, many hosts",
      title: "Use the interface that fits the work — without changing story truth.",
      hosts: [
        ["CLI", "Scriptable automation and inspection."],
        ["Local Web", "Low-overhead creator workstation and first-class product surface."],
        ["Hosted UI", "The same product model behind a remote typed boundary."],
        ["Agent Skill", "Portable bridge access without private persistence imports."],
      ],
    },
    release: {
      eyebrow: "Release truth",
      title: "0.8.x means active pre-1.0 development.",
      lede: "Latest main is the development baseline. Machine contracts are increasingly explicit and CI-gated, but Quillframe does not pretend that every 8.0-line goal is frozen or complete.",
      cta: "Read the changelog",
    },
    final: {
      title: "Read the system. Inspect the proof. Then decide if it fits your fiction workflow.",
      docs: "Browse documentation",
      github: "View on GitHub",
    },
  },
  routes: {
    product: {
      eyebrow: "Product model",
      title: "Quillframe is a fiction production system, not a prompt wrapper.",
      lede: "It separates creative judgment from deterministic control so a long-running book can accumulate evidence, revisions, and state without turning every previous model output into truth.",
      cards: [
        { title: "Authority before convenience", body: "Locked, accepted, active plan, review, proposal, derived, runtime, learning, and corpus material are not interchangeable." },
        { title: "Evidence before confidence", body: "Context and character decisions can expose exactly what support existed, what was eligible, and what actually entered the active packet." },
        { title: "Repair the owning mechanism", body: "Surface clusters regenerate scenes; reader-grip failures return to Reader Pressure and Scene Simulation; story failures return to Story mechanics." },
        { title: "Acceptance is a real boundary", body: "A review candidate is not Canon. User acceptance and exact settlement remain explicit transitions with fingerprints and before/after evidence." },
      ],
    },
    studio: {
      eyebrow: "Quillframe Studio",
      title: "The creative workbench around Core — with progressive disclosure instead of dashboard overload.",
      lede: "Phase 2C now ships a real read-only SolidJS shell: bilingual, mobile-first, loopback-hosted, no default polling, and backed by the public Host Bridge. Local Web remains first-class; Tauri is still optional.",
      cards: [
        { eyebrow: "Phase 1", title: "Run / Context Inspector", body: "Shows the crucial distinction between semantic support and evidence that really entered model context." },
        { eyebrow: "Phase 2A", title: "Project Hub / Scene", body: "A safe read projection for project identity and a creator/inspector scene workspace prototype." },
        { eyebrow: "Phase 2B", title: "Portable Host Bridge", body: "Allowlisted read operations shared by CLI, Local Web/app, hosted UI, and Agent Skill consumers." },
        { eyebrow: "Phase 2C", title: "Real SolidJS product shell", body: "Current main includes the actual app shell, loopback transport, exact-pinned config-generated WeiUI CSS, responsive/i18n product surfaces, deterministic CI, and fingerprint-bound visual QA. It remains intentionally read-only." },
      ],
    },
    architecture: {
      eyebrow: "System architecture",
      title: "Generic mechanisms stay generic. Project truth stays in the project.",
      lede: "Quillframe defines reusable Story, Character, Canon, Context, Quality, Runtime, Learning, Corpus, Publication, and Product contracts. Consumer novels supply their own characters, world, plans, state, manuscript, and accepted Canon.",
      cards: [
        { title: "Harness", body: "Session-native orchestration, capabilities, routing, handoff, and checkpoint semantics." },
        { title: "Context", body: "Sparse question-bounded evidence with visibility, story-order, authority, and hard-budget enforcement." },
        { title: "Semantic contracts", body: "Typed model judgments with fingerprints; deterministic validators enforce shape and ownership, not literary taste." },
        { title: "Quality", body: "Reader, continuity, character, surface, and independent semantic evidence converge at an explicit readiness boundary." },
        { title: "Learning", body: "Evidence-backed preference hypotheses with scope, contradictions, provenance, and rollback." },
        { title: "Publication", body: "Exact-text Accepted manuscript compilation into deterministic, derived publication artifacts." },
      ],
    },
    publication: {
      eyebrow: "Deterministic publication",
      title: "Publication is derived output — never a second manuscript authority.",
      lede: "The current minimum compiler binds to accepted text fingerprints and preserves exact Unicode chapter text. Broader typesetting remains deliberately separate from what is already implemented.",
      cards: [
        { title: "clean_text", body: "A deterministic clean-text representation of Accepted manuscript content." },
        { title: "web_reflow", body: "Reflowable Web HTML derived from the same exact-text Publication IR." },
        { title: "print_book", body: "Print-oriented HTML/CSS. It is not yet the final paged-media PDF pipeline described by the broader Typesetting roadmap." },
        { title: "epub3", body: "Deterministic EPUB 3.3 generation with internal structure/text validation; release conformance requires external EPUBCheck." },
      ],
      note: "Issue #16 remains open for richer semantic IR, fuller profile controls, advanced CJK/Latin typography, paged-media PDF, broader validation, and Studio Publish authoring/preview.",
    },
    docs: {
      eyebrow: "Documentation",
      title: "Deep contracts when you need them. Product story when you do not.",
      lede: "The public site does not replace repository documentation. These links lead to the maintained sources that define current behavior and boundaries.",
      cards: [
        { eyebrow: "Start", title: "Docs Home", body: "Task-oriented entry into architecture, runtime, quality, projects, Studio, and release truth.", meta: "docs/README.en.md" },
        { eyebrow: "Core", title: "Architecture Atlas", body: "Subsystem map and contract-oriented architecture reference.", meta: "docs/architecture-atlas.en.md" },
        { eyebrow: "Production", title: "Production Pipeline", body: "From context freeze and simulation through user-visible review and settlement boundaries.", meta: "docs/production-pipeline.en.md" },
        { eyebrow: "Quality", title: "Quality Assurance", body: "Surface, Reader Engagement, Continuity, and semantic gate semantics.", meta: "docs/quality-assurance.en.md" },
        { eyebrow: "Product", title: "Studio Architecture", body: "Creator/Inspector product model, portable hosts, the real Phase 2C SolidJS shell, WeiUI foundation, and current gaps.", meta: "studio/PRODUCT_ARCHITECTURE.en.md" },
        { eyebrow: "Release", title: "0.8.x Development Inventory", body: "What is merged, what remains open, and what must not be described as shipped.", meta: "docs/8-0-development-inventory.en.md" },
      ],
    },
    changelog: {
      eyebrow: "Release truth",
      title: "A changelog that separates implementation from aspiration.",
      lede: "Quillframe is pre-1.0. The current ledger records merged machine/product behavior and keeps remaining Core/Product gaps explicit rather than silently promoting roadmaps into capabilities.",
      cards: [
        { title: "0.9.0 identity", body: "Manifest, CLI, Skill, Project SDK default, MCP metadata, and documentation governance use one pre-1.0 development identity." },
        { title: "Breaking cleanup is still possible", body: "Before 1.0, justified machine-contract cleanup may land on latest main when architecture and deterministic CI support it." },
        { title: "History stays history", body: "Older 7.x changelog/spec records retain their original meaning; active docs do not rewrite the past to make current naming look inevitable." },
      ],
    },
  } satisfies Record<string, RouteCopy>,
} as const;
