import type { RouteCopy } from "./content";

export const zhCN = {
  languageName: "EN",
  nav: {
    product: "产品",
    studio: "Studio",
    architecture: "架构",
    publication: "出版",
    docs: "知识库",
    changelog: "版本",
    github: "GitHub",
    menu: "打开导航",
    close: "关闭导航",
    appearance: "切换外观",
  },
  home: {
    eyebrow: "AI 原生小说创作框架 · 1.0.0-dev.0",
    title: "让长篇创作有记忆，也有边界。",
    lede: "Quillframe 不只生成文字。它会记录上下文从哪里来、角色此刻能知道什么、候选稿通过了哪些审查，以及正文在接受后如何进入可重复的出版流程。每一步都有边界，也都有证据可查。",
    primaryCta: "看看它怎么工作",
    secondaryCta: "查看系统架构",
    proofLabel: "不是承诺，是证据",
    problem: {
      eyebrow: "真正难的是长期一致",
      title: "一次提示词能写出一段话；长篇小说需要会守规则的记忆。",
      lede: "一次生成并不难。真正困难的是一本书写到几十万字以后，哪些内容算事实、谁在此刻知道什么、哪里改过、哪些证据真的进入了上下文，仍然能够说清楚。",
      cards: [
        { title: "上下文不能只看“相关”", body: "证据即使相关，也要先经过可见性、故事时间顺序、当前阶段、权威等级和上下文预算检查。能被系统找到，不代表此刻应该被模型看到。" },
        { title: "角色不能偷看作者后台", body: "某条信息存在于系统里，并不代表角色已经知道。未来信息、未知信息或与当前视角不兼容的证据，都不能替角色行动背书。" },
        { title: "质量不能被压成一个总分", body: "文本表面、读者参与、连续性和独立语义审查各自保留明确状态。是否可进入审查，是这些必要条件的共同结果，不是一个看起来很专业的“8.7 分”。" },
      ],
    },
    forge: {
      eyebrow: "锻造流程",
      title: "文学判断交给模型，系统边界保持确定。",
      lede: "模型负责判断叙事语义；代码负责权威、可见性、指纹、预算、持久化、类型校验与事务。",
      steps: [
        ["01", "项目", "正典、计划、角色、关系、研究资料与当前工作各自保留清晰的权威等级。"],
        ["02", "上下文", "围绕当前问题选择证据，并在语义判断前先按可见性和故事时间过滤。"],
        ["03", "情节模拟", "先解决因果、角色动机、读者压力与后果，再进入句子层面的润色。"],
        ["04", "候选稿", "生成只使用冻结后的上下文包；私有推理和回归测试材料不进入写作上下文。"],
        ["05", "质量门", "文本表面、读者参与、连续性与必要的独立语义审查，都绑定同一个候选稿指纹。"],
        ["06", "进入审查", "只有满足当前规则的候选稿才能进入用户审查；接受与结算仍是后续独立边界。"],
      ],
    },
    proofs: [
      { eyebrow: "上下文", title: "被判定有帮助 ≠ 真正进入上下文", body: "运行收据会区分：哪些证据被判定为支持材料，哪些最后真的进入了受预算约束的上下文包，以及哪些因为预算或可见性被排除。", meta: "quillframe_run_receipt_v1" },
      { eyebrow: "就绪状态", title: "所有必要审查，都对应同一份候选稿", body: "只要必要的文本表面、读者参与、连续性或独立语义证据缺失、等待中或失败，这份候选稿就不会被标记为可进入用户审查。", meta: "quillframe_production_readiness_v1" },
      { eyebrow: "角色知识", title: "角色知道什么，有故事时间边界", body: "角色是否知道一件事，与它通过什么方式得知，是两件不同的事。角色行动必须由它在当前故事时点真正可见的证据支持。", meta: "角色证据契约" },
      { eyebrow: "出版", title: "接受后的正文保持逐字一致", body: "出版中间表示会核对来源指纹，并在生成纯文本、网页 HTML、面向印刷的 HTML/CSS 和 EPUB 3 时保持接受稿的 Unicode 正文逐字一致。", meta: "quillframe_publication_ir_v1" },
      { eyebrow: "运行方式", title: "能访问，不等于拥有权威", body: "命令行、Desktop、云端界面和 Agent Skill 可以开放不同能力，但运行方式不同不会自动产生正典、框架写入或结算权威。", meta: "authority=false" },
      { eyebrow: "持久化", title: "SQLite 是唯一的规范数据库", body: "全局与项目级 SQLite 通过类型化 Core 边界持久化产品状态；自动保存、修订、接受与结算始终是不同的状态转换。", meta: "SQLite-native" },
    ],
    studio: {
      eyebrow: "Studio",
      title: "先是创作工作台，再是运行检查器。",
      lede: "Writer Mode 从书桌、正文、计划、故事、审查、研究、学习和出版出发；只有需要追溯证据时，Inspector Mode 才展开会话、运行、上下文、模型执行与诊断。",
      bullets: ["SolidJS + TypeScript + Vite", "Tauri 2 轻量桌面宿主", "Borderless Kawaii Editorial", "通过类型化 Host Bridge 访问 Python Core"],
      cta: "查看 Studio",
    },
    publication: {
      eyebrow: "出版",
      title: "接受后的正文，确定地生成每一种派生格式。",
      lede: "出版核心保持接受稿逐字一致，核对来源指纹，再按明确配置生成派生格式；输出不会反过来成为正典。",
      profiles: ["纯文本", "网页", "印刷版", "EPUB"],
      note: "出版产物始终是派生状态。发布级格式校验与正文权威保持分离。",
      cta: "查看出版能力",
    },
    architecture: {
      eyebrow: "系统架构",
      title: "一套系统，各自负责一件事。",
      lede: "Quillframe 不把一群智能体堆成圆桌会。每个子系统只负责边界清晰的机制，再把带类型的证据交给下一层。",
      cards: [
        { eyebrow: "项目", title: "正典与状态", body: "权威等级、依赖、已接受状态、计划和结算证据始终显式存在。" },
        { eyebrow: "宿主边界", title: "宿主运行，Quillframe 管理小说", body: "宿主负责 session、model/tool 循环、sandbox 与 subagent；Quillframe 保持小说契约、Context、评审与 Settlement 语义。" },
        { eyebrow: "故事", title: "情节与角色", body: "因果机制、角色动机、知识边界、关系变化和长线状态对齐属于故事机制。" },
        { eyebrow: "编辑", title: "读者与文本表面", body: "读者压力、参与度、反 AI 文本表面约束、候选稿演进和窄范围修复各有自己的责任边界。" },
        { eyebrow: "证据", title: "语料与学习", body: "语料权限、偏好证据、反例和可回滚假设都保留来源，也不会泄漏成项目正典。" },
        { eyebrow: "产品", title: "Studio 与出版", body: "类型化宿主边界、SQLite 原生持久化、确定性出版与可检查的产品证据都建立在 Core 公开契约之上。" },
      ],
      cta: "查看架构",
    },
    delivery: {
      eyebrow: "一个产品，多种运行方式",
      title: "界面可以不同，故事事实不能变。",
      hosts: [
        ["命令行（CLI）", "适合脚本化自动化与检查。"],
        ["Desktop", "Tauri 2 轻量宿主，通过同一套类型化 Core 边界工作。"],
        ["云端界面", "在配置远程 Core 后，通过认证的类型化边界使用同一套 SolidJS 产品界面。"],
        ["Agent Skill", "可移植地接入 Quillframe，不依赖私有持久化实现。"],
      ],
    },
    release: {
      eyebrow: "版本状态",
      title: "1.0.0-dev.0 是当前 clean-break 验收主线。",
      lede: "Quillframe 1.0 development 把公共 Demo、本地 Studio、Hosted BFF、Python Core、native SQLite schema、Host Bridge v11 与任务型 Docs 统一为一个产品。真实 hosted 与 semantic acceptance 证据尚未完成，因此仍是 pre-release。",
      cta: "查看版本记录",
    },
    final: {
      title: "先理解它如何工作，再看看它留下了什么证据。",
      docs: "浏览知识库",
      github: "查看 GitHub",
    },
  },
  routes: {
    product: {
      eyebrow: "产品模型",
      title: "Quillframe 是小说生产系统，不是提示词外壳。",
      lede: "它把创作判断与确定性控制分开，让一本长期运行的书能持续积累证据、修订和状态，而不是把每一次模型输出都顺手升级成事实。",
      cards: [
        { title: "权威先于方便", body: "锁定内容、已接受内容、当前计划、审查稿、提案、派生状态、运行状态、学习材料和语料材料不能混成一层“记忆”。" },
        { title: "证据先于自信", body: "上下文与角色决策都可以说明：有哪些依据、哪些依据在当前阶段有效、最后哪些真的进入了活动上下文包。" },
        { title: "问题回到真正负责它的机制", body: "文本表面问题回到整场景修复；读者抓力问题回到读者压力与场景模拟；故事问题回到故事机制。" },
        { title: "接受是一道真正的边界", body: "进入审查的候选稿还不是正典。用户接受与精确结算都是显式转换，并绑定指纹和修改前后的证据。" },
      ],
    },
    studio: {
      eyebrow: "Quillframe Studio",
      title: "把创作放在前台，把运行证据留在需要时展开。",
      lede: "1.0 Studio 使用 SolidJS + TypeScript + Vite，桌面方向采用 Tauri 2 轻量宿主；以作者为先的信息架构保持响应式，所有权威运行状态都通过 Host Bridge v11 来自 Core，UI 不直接访问 SQLite。",
      cards: [
        { eyebrow: "创作", title: "Authoring first", body: "书桌、正文、计划、故事、审查、研究、学习和出版是普通作者首先看到的产品结构。" },
        { eyebrow: "运行", title: "真实 Core 工作流", body: "Session、Run、Checkpoint、Context 与 Receipt 消费 Core 的真实投影，不在浏览器里伪造 production state。" },
        { eyebrow: "模型", title: "Model Service", body: "用户只用 API Endpoint + Access Token 连接模型 API；模型发现与能力证据来自运行时，默认始终自动选择模型。" },
        { eyebrow: "检查", title: "需要时再展开证据", body: "高级运行、模型执行、能力与 provenance 细节保留在 Inspector，不把普通创作界面变成基础设施后台。" },
      ],
    },
    architecture: {
      eyebrow: "系统架构",
      title: "通用机制保持通用；项目事实始终属于项目。",
      lede: "Quillframe 定义可复用的故事、角色、正典、上下文、质量、运行时、学习、语料、出版、持久化与产品契约；具体小说自己拥有角色、世界、计划、状态、正文和已接受正典。",
      cards: [
        { title: "运行编排", body: "负责会话级编排、能力、路由、交接和检查点语义。" },
        { title: "上下文", body: "围绕问题建立稀疏证据包，并执行可见性、故事顺序、权威等级和硬预算限制。" },
        { title: "语义契约", body: "模型判断带有明确类型和指纹；确定性校验器负责结构与归属，不冒充文学审美。" },
        { title: "质量", body: "读者、连续性、角色、文本表面和独立语义证据，在显式就绪边界汇合。" },
        { title: "持久化", body: "SQLite 是规范持久化状态；schema fragment、WAL、完整性检查、修订、备份与 blob 都由 Core 拥有。" },
        { title: "出版", body: "从已接受正文的精确文本出发，生成确定性的派生出版产物。" },
      ],
    },
    publication: {
      eyebrow: "确定性出版",
      title: "出版是派生输出，不是第二份正文权威。",
      lede: "编译器绑定已接受正文的来源指纹，并保持每章 Unicode 文本逐字一致；更大的排版能力仍与正文权威明确分开。",
      cards: [
        { title: "纯文本", body: "把已接受正文确定地整理为纯文本表示。" },
        { title: "可重排网页", body: "从同一份精确文本出版中间表示生成可重排网页 HTML。" },
        { title: "印刷版", body: "从已接受正文生成面向印刷的 HTML/CSS，而不是创造第二份可编辑正文。" },
        { title: "EPUB 3", body: "确定生成 EPUB 3，并让格式验证与正典权威保持分离。" },
      ],
      note: "出版产物来自已接受源状态，不会成为第二套 live authority。",
    },
    docs: {
      eyebrow: "知识库",
      title: "先理解产品，需要深入时再读契约。",
      lede: "这里把持续维护、与当前实现同步的仓库文档编译进产品本身。日常阅读不必离开站点；需要核对来源时仍可以追溯到仓库。",
      cards: [
        { eyebrow: "入门", title: "知识库首页", body: "按任务进入架构、运行时、质量、项目、Studio 与版本状态。", meta: "docs/README.zh-CN.md" },
        { eyebrow: "核心", title: "架构图谱", body: "按子系统与契约浏览 Quillframe 的整体架构。", meta: "docs/architecture-atlas.zh-CN.md" },
        { eyebrow: "生产", title: "生产流水线", body: "从上下文冻结与情节模拟，一直到用户审查和结算边界。", meta: "docs/production-pipeline.zh-CN.md" },
        { eyebrow: "质量", title: "质量保障", body: "解释文本表面、读者参与、连续性和语义审查各自如何工作。", meta: "docs/quality-assurance.zh-CN.md" },
        { eyebrow: "产品", title: "Studio 架构", body: "Writer / Inspector 产品模型、类型化 Host Bridge、SolidJS Studio、Tauri 宿主方向与当前边界。", meta: "studio/PRODUCT_ARCHITECTURE.zh-CN.md" },
        { eyebrow: "版本", title: "开发记录", body: "历史版本、1.0 clean break、精确评审证据与尚未满足的验收门槛。", meta: "CHANGELOG.zh-CN.md" },
      ],
    },
    changelog: {
      eyebrow: "版本状态",
      title: "版本记录只写已经发生的事。",
      lede: "Quillframe 正处于 1.0 development acceptance。当前记录会明确区分已实现行为与仍需真实账号或真实语义执行的门槛。",
      cards: [
        { title: "统一使用 1.0.0-dev.0 身份", body: "Manifest、CLI、Studio、持久化、协议与文档共用同一个 pre-release identity。" },
        { title: "Clean break", body: "1.0 之前的 state、route、CLI command、protocol version 与 mapped layout 都会被拒绝，不会被翻译。" },
        { title: "诚实门槛", body: "Hosted deployment 与真实 semantic acceptance 在获得当前证据前保持 pending。" },
      ],
    },
  } satisfies Record<string, RouteCopy>,
} as const;
