import { For, Show, createMemo, createSignal } from "solid-js";
import type { Locale } from "./content";
import { inspectProjectFiles, type NativeManifest, type NativeContext, type ProjectInspection } from "./project-inspector-contract";
type Props = { locale: Locale };

const requiredDirectories = [".quillframe/data"];
const evidenceDirectories = ["evals", "tests", "regressions"];

function demoInspection(): ProjectInspection {
  const project: NativeManifest = { schema: "quillframe_project_v1_0", id: "MOONLIT-ARCHIVE", title: "Moonlit Archive", language: "zh-CN", chapter_scope: "CH001" };
  const context: NativeContext = { context_schema: "quillframe_project_context_v1_0", manifest: project, manifest_fingerprint: "sha256:" + "a".repeat(64), chapter_scope: "CH001", data_boundary: ".quillframe/data", authority: false };
  return { rootName: "moonlit-archive", fileCount: 84, totalBytes: 1842770, project, context, status: "coherent", legacy_metadata_rejected: false, checks: [{ key: "manifest", state: "pass", title: "quillframe.toml", detail: "quillframe_project_v1_0 · five keys" }, { key: "context", state: "pass", title: "quillframe_project_context_v1_0", detail: "CH001 · authority=false" }, { key: "fingerprint", state: "pass", title: "manifest_fingerprint", detail: context.manifest_fingerprint }, { key: "boundary", state: "pass", title: ".quillframe/data", detail: "native data boundary present" }], directories: [...requiredDirectories, ...evidenceDirectories].map((name) => ({ name, present: true })) };
}

function humanBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }

export default function ProjectInspector(props: Props) {
  const [inspection, setInspection] = createSignal<ProjectInspection>();
  const [busy, setBusy] = createSignal(false);
  const [error, setError] = createSignal("");
  const zh = () => props.locale === "zh-CN";
  const text = createMemo(() => zh() ? { eyebrow: "Project Import · Browser-native", title: "把项目拖进来，先确认它的 native identity。", lede: "只在浏览器里读取五键 manifest、context v1_0、CH001、fingerprint 与 .quillframe/data。不会上传，旧 metadata 只会被拒绝。", select: "选择项目文件夹", demo: "载入示例项目", privacy: "本地读取 · 不上传", emptyTitle: "选择一个 Quillframe Project", emptyBody: "检查器只接受 quillframe.toml 的五个键，并展示 native context 与 .quillframe/data。", summary: "项目摘要", checks: "Native contract checks", structure: "Native data boundary", structuralOnly: "这是 browser-side structural inspection，不等于 Core authority 或 production readiness。", coherent: "Native contract coherent", scaffold: "Native manifest 无效", incomplete: "缺少 native manifest", conflict: "Legacy metadata rejected", files: "文件", size: "读取规模", reset: "检查另一个项目", invalid: "无法读取这些文件，请重新选择项目文件夹。" } : { eyebrow: "Project Import · Browser-native", title: "Drop in a project and verify its native identity.", lede: "Reads the five-key manifest, context v1_0, CH001, fingerprint, and .quillframe/data locally. Nothing is uploaded; legacy metadata is rejected.", select: "Choose project folder", demo: "Load demo project", privacy: "Local read · no upload", emptyTitle: "Choose a Quillframe Project", emptyBody: "The inspector accepts only the five-key quillframe.toml and shows the native context and .quillframe/data boundary.", summary: "Project summary", checks: "Native contract checks", structure: "Native data boundary", structuralOnly: "This is browser-side structural inspection, not Core authority or production readiness.", coherent: "Native contract coherent", scaffold: "Native manifest invalid", incomplete: "Native manifest missing", conflict: "Legacy metadata rejected", files: "Files", size: "Read size", reset: "Inspect another project", invalid: "Could not inspect those files. Choose the project folder again." });
  const statusLabel = () => { const status = inspection()?.status; return status ? text()[status] : ""; };
  const ingest = async (files: FileList | File[]) => { if (!files.length) return; setBusy(true); setError(""); try { setInspection(await inspectProjectFiles(files, zh())); } catch { setError(text().invalid); } finally { setBusy(false); } };
  let folderInput: HTMLInputElement | undefined;
  return <div class="project-inspector-shell">
    <section class="project-inspector-intro"><div><p class="eyebrow">{text().eyebrow}</p><h1>{text().title}</h1><p>{text().lede}</p></div><span class="wui-badge wui-badge--success inspector-privacy">⌁ {text().privacy}</span></section>
    <Show when={inspection()} fallback={<section class="wui-card inspector-dropzone" onDragOver={(event) => { event.preventDefault(); if (event.dataTransfer) event.dataTransfer.dropEffect = "copy"; }} onDrop={(event) => { event.preventDefault(); if (event.dataTransfer) void ingest(event.dataTransfer.files); }}><div class="inspector-drop-icon" aria-hidden="true">⌂</div><h2>{text().emptyTitle}</h2><p>{text().emptyBody}</p><div class="inspector-actions"><button class="wui-button wui-button--solid" type="button" disabled={busy()} onClick={() => folderInput?.click()}>{busy() ? "…" : text().select}</button><button class="wui-button wui-button--soft" type="button" onClick={() => setInspection(demoInspection())}>✦ {text().demo}</button></div><input ref={(element) => { folderInput = element; element.setAttribute("webkitdirectory", ""); element.setAttribute("directory", ""); }} class="inspector-file-input" type="file" multiple onChange={(event) => { const files = event.currentTarget.files; if (files) void ingest(files); }} /><Show when={error()}><p class="inspector-error" role="alert">{error()}</p></Show><div class="inspector-cli"><div><strong>{zh() ? "还没有项目？" : "No project yet?"}</strong><span>{zh() ? "使用 native launch 创建一个项目：" : "Create one with the native launch command:"}</span></div><code>quillframe launch ./my-novel --new --id PROJECT-X --title "My Novel" --language en</code></div></section>}>
      {(result) => <><section class="wui-card inspector-summary-card" data-status={result().status}><div class="inspector-summary-heading"><div><p class="eyebrow">{text().summary}</p><h2>{result().project.title || result().rootName}</h2><p>{result().rootName}</p></div><span class="inspector-status-badge" data-state={result().status}>{statusLabel()}</span></div><div class="inspector-stat-grid"><div><span>{text().files}</span><strong>{result().fileCount}</strong></div><div><span>{text().size}</span><strong>{humanBytes(result().totalBytes)}</strong></div><div><span>Project ID</span><strong>{result().project.id || "—"}</strong></div><div><span>Language</span><strong>{result().project.language || "—"}</strong></div></div></section><div class="inspector-dashboard-grid"><section class="wui-card inspector-panel"><div class="inspector-panel-heading"><span>✓</span><div><p class="eyebrow">{text().checks}</p><h2>{text().checks}</h2></div></div><div class="inspector-check-list"><For each={result().checks}>{(check) => <div class="inspector-check" data-state={check.state}><span class="inspector-check-icon" aria-hidden="true">{check.state === "pass" ? "✓" : check.state === "warn" ? "!" : "×"}</span><div><strong>{check.title}</strong><p>{check.detail}</p></div></div>}</For></div></section><section class="wui-card inspector-panel inspector-identity-panel"><div class="inspector-panel-heading"><span>⌘</span><div><p class="eyebrow">Native context</p><h2>Native context</h2></div></div><dl class="inspector-kv"><div><dt>Schema</dt><dd>{result().context?.context_schema || result().project.schema || "—"}</dd></div><div><dt>Chapter</dt><dd>{result().context?.chapter_scope || result().project.chapter_scope || "—"}</dd></div><div><dt>Fingerprint</dt><dd><code>{result().context?.manifest_fingerprint || "—"}</code></dd></div><div><dt>Boundary</dt><dd><code>{result().context?.data_boundary || ".quillframe/data"}</code></dd></div><div><dt>Authority</dt><dd>false</dd></div></dl></section></div><section class="wui-card inspector-structure-panel"><div class="inspector-structure-heading"><div><p class="eyebrow">{text().structure}</p><h2>{text().structure}</h2></div><button type="button" class="wui-button wui-button--soft" onClick={() => setInspection(undefined)}>{text().reset}</button></div><div class="inspector-directory-grid"><For each={result().directories}>{(directory) => <div class="inspector-directory" data-present={directory.present}><span aria-hidden="true">{directory.present ? "●" : "○"}</span><code>{directory.name}/</code></div>}</For></div><p class="inspector-disclaimer">{text().structuralOnly}</p></section></>}
    </Show>
  </div>;
}
