import { For, Show, createMemo, createSignal, onMount } from "solid-js";
import { useLocation, useSearchParams } from "@solidjs/router";
import { invokeBridge, operationError } from "../bridge";
import { useI18n } from "../i18n";

export default function ProjectLens(){
 const {locale}=useI18n(); const zh=createMemo(()=>locale()==="zh-CN"); const t=(e:string,c:string)=>zh()?c:e; const loc=useLocation(); const [p]=useSearchParams(); const project=()=>String(p.project||localStorage.getItem("quillframe.ui.lastProjectId")||""); const [data,setData]=createSignal<any>(); const [error,setError]=createSignal<string>();
 const cfg=createMemo(()=>loc.pathname==="/plan"?{op:"plan.inspect",title:t("Plan","计划"),note:t("Plan edits are deferred until a typed authority contract exists.","Plan 编辑在 typed authority contract 存在前保持 deferred。")}:loc.pathname==="/story"?{op:"story.inspect",title:t("Story","故事"),note:t("Authority labels are textual; this lens never mutates Canon.","Authority 使用文字标签；此视图绝不直接修改 Canon。")}:loc.pathname==="/research"?{op:"research.inspect",title:t("Research & Corpus","研究与语料"),note:t("Research and corpus are evidence, not Canon or character knowledge.","Research 与 Corpus 是 evidence，不是 Canon，也不是角色知识。")}: {op:"inspector.learning.list",title:t("Learning","学习"),note:t("Captured evidence does not auto-promote preferences or Framework rules.","捕获 evidence 不会自动提升为 preference 或 Framework 规则。")});
 onMount(async()=>{if(!project())return;try{const r=await invokeBridge<any>(cfg().op,{project_id:project(),limit:200});if(r.status!=="ok"||!r.data)throw new Error(operationError(r));setData(r.data)}catch(e){setError(e instanceof Error?e.message:String(e))}});
 const entries=()=>data()?Object.entries(data()).filter(([k])=>!["schema","project_id","authority","mutation_supported","research_is_canon","corpus_is_canon"].includes(k)):[];
 return <section class="nf-page nf-authoring-canvas"><header class="nf-manuscript-header"><div><span class="nf-eyebrow">{cfg().op}</span><h1>{cfg().title}</h1><p>{cfg().note}</p></div><span class="wui-badge wui-badge--outline">authority=false</span></header><Show when={project()} fallback={<p>{t("Choose a project first.","请先选择 Project。")}</p>}><For each={entries()}>{([name,value])=><section class="nf-editorial-section"><div class="nf-section-heading"><span class="nf-eyebrow">CORE</span><h2>{name}</h2></div><Show when={Array.isArray(value)} fallback={<pre class="wui-code-block"><code>{JSON.stringify(value,null,2)}</code></pre>}><div class="nf-lens-list"><For each={value as any[]}>{(item)=><article class="nf-lens-row"><Show when={item?.authority_class||item?.canon_status||item?.status||item?.state}>{(a)=><span class="wui-badge wui-badge--outline">{String(a())}</span>}</Show><pre><code>{JSON.stringify(item,null,2)}</code></pre></article>}</For></div></Show></section>}</For></Show><Show when={error()}><div class="wui-alert" role="alert"><div class="wui-alert__body"><strong>{error()}</strong></div></div></Show></section>
}
