export type BridgeStatus="ok"|"invalid"|"unsupported"|"failed"|"error";
export type StudioSurface="local_app"|"hosted_web"|"tauri_local";
export type OperationKind="query"|"command"|"authority_command";
const REQUEST_SCHEMA="quillframe_studio_host_bridge_request_v1" as const,TOKEN_PLACEHOLDER="__QUILLFRAME_STUDIO_TOKEN__";
export interface BridgeRequest{schema:typeof REQUEST_SCHEMA;request_id:string;operation:string;surface:StudioSurface;args:Record<string,unknown>;authority:false}
export interface BridgeResult<T=unknown>{schema:"quillframe_studio_host_bridge_result_v1";request_id:string;operation:string;surface:StudioSurface;status:BridgeStatus;request_fingerprint:string;result_fingerprint:string;data:T|null;error:unknown;authority:false;canon_authority:false;framework_write_authority:false;settlement_authority:false}
export interface OperationContract{kind:OperationKind;required_args:string[];allowed_surfaces?:Array<StudioSurface|"cli"|"agent_package">}
export interface BridgeDescription{schema:"quillframe_studio_host_bridge_description_v1";framework_version:string;contract_schema:string;contract_version:string;product_model:"one_product_one_core_many_transports";surface:StudioSurface|"cli"|"agent_package";supported_operations:string[];operation_contracts:Record<string,OperationContract>;deferred_operations:Record<string,string>;authority:false;canon_authority:false;framework_write_authority:false;settlement_authority:false;direct_core_store_access:false}
export interface BridgeTransport{readonly surface:StudioSurface;readonly name:"local-http"|"hosted-http"|"tauri-ipc";available():boolean;invoke<T>(request:BridgeRequest):Promise<BridgeResult<T>>}
declare global{interface Window{__TAURI__?:{core?:{invoke?:<T>(command:string,args?:Record<string,unknown>)=>Promise<T>}}}}
const meta=(name:string)=>document.querySelector<HTMLMetaElement>(`meta[name="${name}"]`)?.content.trim()??"";
const localToken=()=>meta("quillframe-studio-token");
const hostedEndpoint=()=>{const configured=meta("quillframe-studio-hosted-endpoint");if(configured)return configured.replace(/\/$/,"");const vite=import.meta.env.VITE_QUILLFRAME_BRIDGE_URL?.trim();return vite?vite.replace(/\/$/,""):""};
function assertEnvelope<T>(value:unknown,surface:StudioSurface):asserts value is BridgeResult<T>{if(!value||typeof value!=="object")throw new Error("Bridge returned a non-object response");const c=value as Partial<BridgeResult<T>>;if(c.schema!=="quillframe_studio_host_bridge_result_v1")throw new Error("Unexpected bridge result schema");if(c.surface!==surface)throw new Error(`Bridge surface mismatch: expected ${surface}`);if(c.authority!==false||c.canon_authority!==false||c.framework_write_authority!==false||c.settlement_authority!==false)throw new Error("Bridge authority invariant violated")}
async function httpResult<T>(r:Response,s:StudioSurface){const value:unknown=await r.json().catch(()=>null);if(!r.ok)throw new Error(value&&typeof value==="object"&&"message" in value?String((value as any).message):`HTTP ${r.status}`);assertEnvelope<T>(value,s);return value}
export class LocalHttpTransport implements BridgeTransport{readonly surface="local_app" as const;readonly name="local-http" as const;available(){const v=localToken();return v.length>0&&v!==TOKEN_PLACEHOLDER}async invoke<T>(request:BridgeRequest){if(!this.available())throw new Error("Local Quillframe Core host is not bound");return httpResult<T>(await fetch("/api/bridge/invoke",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","X-Quillframe-Studio-Token":localToken()},body:JSON.stringify(request)}),this.surface)}}
export class HostedHttpTransport implements BridgeTransport{readonly surface="hosted_web" as const;readonly name="hosted-http" as const;available(){return hostedEndpoint().length>0}async invoke<T>(request:BridgeRequest){const endpoint=hostedEndpoint();if(!endpoint)throw new Error("Hosted Quillframe Core endpoint is not configured");return httpResult<T>(await fetch(`${endpoint}/api/bridge/invoke`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(request)}),this.surface)}}
export class TauriTransport implements BridgeTransport{readonly surface="tauri_local" as const;readonly name="tauri-ipc" as const;available(){return typeof window.__TAURI__?.core?.invoke==="function"}async invoke<T>(request:BridgeRequest){const invoke=window.__TAURI__?.core?.invoke;if(!invoke)throw new Error("Tauri Quillframe Core host is unavailable");const value=await invoke<unknown>("bridge_invoke",{request});assertEnvelope<T>(value,this.surface);return value}}
function detect(){const t=new TauriTransport();if(t.available())return t;const l=new LocalHttpTransport();if(l.available())return l;const h=new HostedHttpTransport();if(h.available())return h;return null}
export class BridgeClient{constructor(private readonly transport:BridgeTransport){}get surface(){return this.transport.surface}get transportName(){return this.transport.name}async invoke<T=unknown>(operation:string,args:Record<string,unknown>={}){return this.transport.invoke<T>({schema:REQUEST_SCHEMA,request_id:crypto.randomUUID(),operation,surface:this.transport.surface,args,authority:false})}describe(){return this.invoke<BridgeDescription>("bridge.describe")}}
let singleton:BridgeClient|null|undefined;export function bridgeClient(){if(singleton===undefined){const t=detect();singleton=t?new BridgeClient(t):null}return singleton}export const bridgeTransportAvailable=()=>bridgeClient()!==null;export const studioSurface=():StudioSurface=>bridgeClient()?.surface??"hosted_web";export const bridgeTransportName=()=>bridgeClient()?.transportName??"unbound";
export async function invokeBridge<T=unknown>(operation:string,args:Record<string,unknown>={}){const client=bridgeClient();if(!client)throw new Error("Quillframe Core host is not bound to this Studio surface");return client.invoke<T>(operation,args)}
export function operationError(result:BridgeResult<unknown>){if(!result.error)return result.status;if(typeof result.error==="string")return result.error;if(typeof result.error==="object"&&result.error&&"message" in result.error)return String((result.error as any).message);try{return JSON.stringify(result.error)}catch{return String(result.error)}}
