import { Suspense, lazy, type JSX } from "solid-js";
import { render } from "solid-js/web";
import { Route, Router } from "@solidjs/router";
import { AppShell } from "./AppShell";
import { StudioFailureBoundary, StudioNotFound, StudioRouteLoading, StudioSkipLink } from "./StudioResilience";
import { bridgeTransportAvailable } from "./bridge";
import { I18nProvider } from "./i18n";
import { StudioProvider } from "./studio";
import "./styles/index.css";
const Desk=lazy(()=>import("./routes/Desk")),Start=lazy(()=>import("./routes/Start")),Manuscript=lazy(()=>import("./routes/Manuscript")),Review=lazy(()=>import("./routes/Review")),ProjectLens=lazy(()=>import("./routes/ProjectLens")),Project=lazy(()=>import("./routes/Project")),Inspector=lazy(()=>import("./routes/InspectorRoute")),Control=lazy(()=>import("./routes/Control")),Architecture=lazy(()=>import("./routes/Architecture")),Publication=lazy(()=>import("./routes/Publication")),Workspace=lazy(()=>import("./routes/Workspace")),Agents=lazy(()=>import("./routes/Agents")),RuntimeRoute=lazy(()=>import("./routes/Runtime")),ContextRoute=lazy(()=>import("./routes/Context")),Capabilities=lazy(()=>import("./routes/Capabilities")),Semantic=lazy(()=>import("./routes/Semantic")),Diagnostics=lazy(()=>import("./routes/Diagnostics")),Settings=lazy(()=>import("./routes/Settings"));
const root=document.getElementById("app");if(!root)throw new Error("#app mount point is missing");document.documentElement.dataset.experience="story-loom-kawaii-atelier-v5";document.documentElement.dataset.productLanguage="quillframe-kawaii-v1";
function StudioShellRoot(props:{children?:JSX.Element}){return <AppShell><Suspense fallback={<StudioRouteLoading/>}>{props.children}</Suspense></AppShell>}
async function configureOfflineShell(){if(!("serviceWorker" in navigator))return;if(bridgeTransportAvailable()){const rs=await navigator.serviceWorker.getRegistrations();await Promise.all(rs.filter(r=>{const u=r.active?.scriptURL??r.waiting?.scriptURL??r.installing?.scriptURL;return u?new URL(u).pathname==="/sw.js":false}).map(r=>r.unregister()));return}window.addEventListener("load",()=>{void navigator.serviceWorker.register("/sw.js",{scope:"/",updateViaCache:"none"}).catch(()=>undefined)},{once:true})}void configureOfflineShell().catch(()=>undefined);
render(()=><I18nProvider><StudioProvider><StudioFailureBoundary><StudioSkipLink/><Router root={StudioShellRoot}><Route path="/" component={Desk}/><Route path="/start" component={Start}/><Route path="/manuscript" component={Manuscript}/><Route path="/plan" component={ProjectLens}/><Route path="/story" component={ProjectLens}/><Route path="/review" component={Review}/><Route path="/research" component={ProjectLens}/><Route path="/learning" component={ProjectLens}/><Route path="/project" component={Project}/><Route path="/inspect" component={Inspector}/><Route path="/control" component={Control}/><Route path="/architecture" component={Architecture}/><Route path="/publication" component={Publication}/><Route path="/workspace" component={Workspace}/><Route path="/agents" component={Agents}/><Route path="/runtime" component={RuntimeRoute}/><Route path="/context" component={ContextRoute}/><Route path="/capabilities" component={Capabilities}/><Route path="/semantic" component={Semantic}/><Route path="/diagnostics" component={Diagnostics}/><Route path="/settings" component={Settings}/><Route path="*404" component={StudioNotFound}/></Router></StudioFailureBoundary></StudioProvider></I18nProvider>,root);
