import {createContext,createResource,createSignal,ParentComponent,useContext} from "solid-js";
import {BridgeDescription,BridgeResult,StudioSurface,bridgeTransportAvailable,invokeBridge,operationError,studioSurface} from "./bridge";
interface CoreProjectInspect{schema:string;project:{project_id:string;title:string;language:string;project_schema_version:number;created_at?:string;updated_at?:string};counts?:Record<string,number>;authority:false}
export interface ProjectInspectData{valid:boolean;errors:unknown[];schema:string;authority:false;counts?:Record<string,number>;project:{project_id:string;title:string;language:string;project_schema_version:number;created_at?:string;updated_at?:string;project:{id:string;title:string;version:string|null;language:string;layout:string|null;project_schema_version:string};framework_lock:Record<string,unknown>;logical_paths:Record<string,never>;policy_availability:Record<string,boolean>;unavailable:string[];projection_fingerprint:string}}
interface StudioValue{surface:()=>StudioSurface;bridgeAvailable:()=>boolean;bridgeDescription:()=>BridgeDescription|undefined;bridgeError:()=>unknown;bridgeLoading:()=>boolean;refreshBridge:()=>void;projectId:()=>string;setProjectId:(v:string)=>void;projectRoot:()=>string;setProjectRoot:(v:string)=>void;projectResult:()=>BridgeResult<ProjectInspectData>|undefined;projectLoading:()=>boolean;projectError:()=>string|undefined;inspectProject:(id?:string)=>Promise<void>}
const StudioContext=createContext<StudioValue>();
export const StudioProvider:ParentComponent=(props)=>{const surface=studioSurface(),hasBridge=bridgeTransportAvailable();const [bridge,{refetch}]=createResource(()=>hasBridge?"bound":undefined,async()=>{const r=await invokeBridge<BridgeDescription>("bridge.describe");if(r.status!=="ok"||!r.data)throw new Error(operationError(r));return r.data});const [projectId,setProjectIdSignal]=createSignal(localStorage.getItem("quillframe.ui.lastProjectId")||""),[projectResult,setProjectResult]=createSignal<BridgeResult<ProjectInspectData>>(),[projectLoading,setProjectLoading]=createSignal(false),[projectError,setProjectError]=createSignal<string>();const setProjectId=(v:string)=>{const n=v.trim();setProjectIdSignal(n);if(n)localStorage.setItem("quillframe.ui.lastProjectId",n)};
 const inspectProject=async(requested=projectId())=>{if(!hasBridge){setProjectError("Quillframe Core host is not bound to this Studio surface");return}const id=requested.trim();if(!id){setProjectError("project_id is required");return}setProjectId(id);setProjectLoading(true);setProjectError(undefined);try{const raw=await invokeBridge<CoreProjectInspect>("project.inspect",{project_id:id});if(raw.status!=="ok"||!raw.data){setProjectResult(raw as unknown as BridgeResult<ProjectInspectData>);setProjectError(operationError(raw));return}const p=raw.data.project;const compat:ProjectInspectData={valid:true,errors:[],schema:raw.data.schema,authority:false,counts:raw.data.counts,project:{...p,project:{id:p.project_id,title:p.title,version:null,language:p.language,layout:null,project_schema_version:String(p.project_schema_version)},framework_lock:{status:"not_projected_by_product_core"},logical_paths:{},policy_availability:{},unavailable:["framework_lock","logical_paths"],projection_fingerprint:raw.result_fingerprint}};setProjectResult({...raw,data:compat} as BridgeResult<ProjectInspectData>)}catch(e){setProjectError(e instanceof Error?e.message:String(e))}finally{setProjectLoading(false)}};
 const value:StudioValue={surface:()=>surface,bridgeAvailable:()=>hasBridge,bridgeDescription:()=>bridge(),bridgeError:()=>bridge.error,bridgeLoading:()=>hasBridge&&bridge.loading,refreshBridge:()=>{if(hasBridge)void refetch()},projectId,setProjectId,projectRoot:projectId,setProjectRoot:setProjectId,projectResult,projectLoading,projectError,inspectProject};return <StudioContext.Provider value={value}>{props.children}</StudioContext.Provider>};
export function useStudio(){const v=useContext(StudioContext);if(!v)throw new Error("StudioProvider is missing");return v}
