[package]
name = "quillframe-secrets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
quillframe-core.workspace = true

[target.'cfg(windows)'.dependencies]
keyring = { version = "=3.6.3", features = ["windows-native"] }

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { version = "=3.6.3", features = ["crypto-rust", "linux-native-sync-persistent"] }
